# Generated by Django 4.1.7 on 2023-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_address_email_address_firstname_address_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator')], max_length=20, null=True),
        ),
    ]
