# Generated by Django 4.1.7 on 2023-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_address_city_alter_userprofile_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hydrabad', 'Hydrabad'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hydrabad', 'Hydrabad'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Tamilnadu', 'Tamilnadu'), ('Karnataka', 'Karnataka'), ('AndraPradesh', 'AndraPradesh')], max_length=20, null=True),
        ),
    ]
