# Generated by Django 4.1.7 on 2023-03-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
