# Generated by Django 4.1.7 on 2023-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad')], max_length=20, null=True),
        ),
    ]
