# Generated by Django 4.1.7 on 2023-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0032_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
    ]
