# Generated by Django 4.1.7 on 2023-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai')], max_length=20, null=True),
        ),
    ]
