# Generated by Django 4.1.7 on 2023-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0040_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
