# Generated by Django 4.1.7 on 2023-03-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0048_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator')], max_length=20, null=True),
        ),
    ]
