# Generated by Django 4.1.7 on 2023-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0053_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator')], max_length=20, null=True),
        ),
    ]
