# Generated by Django 4.1.7 on 2023-03-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varientname', models.CharField(max_length=100, null=True)),
                ('varstock', models.PositiveIntegerField(null=True)),
                ('proname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adminapp.product')),
            ],
        ),
    ]
