# Generated by Django 4.1.7 on 2023-03-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_product_stock_productvarient'),
        ('productapp', '0003_coupon_order_usercoupon_payment_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='provar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productvarient'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='provar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productvarient'),
        ),
    ]
