# Generated by Django 4.1.7 on 2023-03-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_banner'),
        ('productapp', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='productvarient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productvarient'),
        ),
    ]
