# Generated by Django 4.1.7 on 2023-03-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_product_price_productvarient_varprice'),
        ('productapp', '0006_orderproduct_productvarient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productimage'),
        ),
    ]
