# Generated by Django 4.1.7 on 2023-03-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_orderproduct_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='img',
        ),
    ]
